version: 2
updates:
  - directory: /
    package-ecosystem: gomod
    schedule:
      interval: daily
    groups:
      go:
        patterns:
          - "*"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - "*"

