version: 2
updates:
  - directory: /
    package-ecosystem: gomod
    schedule:
      interval: daily
    assignees:
      - "klusoga"
    groups:
      go:
        patterns:
          - "*"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: "daily"
    assignees:
      - "klusoga"
    groups:
      github:
        patterns:
          - "*"

